export const CREATE_TASKS = "TASKS_CREATE_REQUESTED";
export const CREATE_TASKS_SUCCEEDED = "TASKS_CREATE_SUCCEEDED";
export const CREATE_TASKS_FAILED = "TASKS_CREATE_FAILED";

export const FETCH_TASKS = "TASKS_FETCH_REQUESTED";
export const FETCH_TASKS_SUCCEEDED = "TASKS_FETCH_SUCCEEDED";
export const FETCH_TASKS_FAILED = "TASKS_FETCH_FAILED";

export const DELETE_TASK = "TASKS_DELETE_REQUESTED";
export const DELETE_TASK_SUCCEEDED = "TASKS_DELETE_SUCCEDED";
export const DELETE_TASK_FAILED = "TASK_DELETE_FAILED";

export const UPDATE_TASK = "TASK_UPDATE_REQUESTED";
export const UPDATE_TASK_SUCCEEDED = "TASK_UPDATE_SUCCEEDED";
export const UPDATE_TASK_FAILED = "TASK_UPDATE_FAILED";
